/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class InformeV extends javax.swing.JFrame {

    /**
     * Creates new form InformeV
     */
    public InformeV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMayor = new javax.swing.JLabel();
        labelMenor = new javax.swing.JLabel();
        labelPromedio = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelMayor.setText("Producto precio mayor:  ");

        labelMenor.setText("Producto precio menor:  ");

        labelPromedio.setText("Promedio de precios:  ");

        labelInventario.setText("Valor de inventario:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMenor)
                    .addComponent(labelMayor)
                    .addComponent(labelPromedio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelInventario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelMayor)
                .addGap(30, 30, 30)
                .addComponent(labelMenor)
                .addGap(31, 31, 31)
                .addComponent(labelPromedio)
                .addGap(32, 32, 32)
                .addComponent(labelInventario)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeV().setVisible(true);
            }
        });
    }

    public String getLabelInventario() {
        return labelInventario.getText();
    }

    public String getLabelMayor() {
        return labelMayor.getText();
    }

    public String getLabelMenor() {
        return labelMenor.getText();
    }

    public String getLabelPromedio() {
        return labelPromedio.getText();
    }

    public void setInventario(String inventario) {
        labelInventario.setText(inventario);
    }

    public void setMayor(String mayor) {
        labelMayor.setText(mayor);
    }

    public void setMenor(String menor) {
        labelMenor.setText(menor);
    }

    public void setPromedio(String promedio) {
        labelPromedio.setText(promedio);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelMayor;
    private javax.swing.JLabel labelMenor;
    private javax.swing.JLabel labelPromedio;
    // End of variables declaration//GEN-END:variables
}
